name: Build and Push to IBM Cloud Container Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Login to IBM Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: us.icr.io
          username: iamapikey
          password: ${{ secrets.ICR_APIKEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            us.icr.io/${{ secrets.ICR_NAMESPACE }}/${{ secrets.ICR_IMAGE}}:latest
            us.icr.io/${{ secrets.ICR_NAMESPACE }}/${{ secrets.ICR_IMAGE}}:${{ env.SHORT_SHA }}