name: Python Tests

on:
  pull_request:
    branches: [ main ]
  # Run tests when Dependabot opens a PR
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Playwright test browser
      run: |
        playwright install chromium
    - name: Test with pytest
      run: |
        pytest
